### ISSUE TITLE
Run task before running mix

### ISSUE THREAD

**Issue by ghost** [mikesaintsg/laravel-mix-serve#1]
This is a feature request.

I need the ability to run some commands to build routes and translations before mix runs.

Would it be possible to add a before or after flag so a user can choose when they should run?

That would be super if it's possible.

Thanks.

**Comment by mikesaintsg** [comment]
Thanks @19peaches 

It's been some time since I've looked into this package, I'll dive in again to see what I can do.

Do you have any examples of what you want to run?

Let me know

**Comment by 19peaches** [comment]
Hey Mike.

I need to run Ziggy and my own package Zora before javascript is compiled. These are javascript route and translation converters that allow the use of Laravel routes and translation in javascript components, so obviously they need to be built first before the js is compiled by webpack

Right now I'm running them in my package.json file, but it's an ugly hack.

1. run `php artisan ziggy:generate`
2. run `php artisan zora:generate`
3. proceed with compiling via mix

I was just thinking that there should be a method that runs before or after with a default of after.

```
mix.serve.before('php artisan ziggy:generate')
   .serve.before('php artisan zora:generate')
```
or perhaps with a boolean argument to denote that it should run first

```
mix.serve('php artisan ziggy:generate', true)
   .serve('php artisan zora:generate', true)
```

Let me know what you can do.

**Comment by mikesaintsg** [comment]
Hi Vince,

Sorry for taking so long to get to this, I have bumped this package to v2.2.0 and added the 'hook' configuration option. 

This allows you to choose which compiler hook you want to use:  https://webpack.js.org/api/compiler-hooks/

```js
mix.serve('php artisan ziggy:generate && php artisan zora:generate', 
    { hook: 'beforeCompile' });
```

This way you have more freedom to choose when to run the command, and you won't have to depend on the package having the method available.

Let me know your thoughts!

**Comment by 19peaches** [comment]
Hey Mike,

Sorry it's taken me so long to get back to you.

I'll try this right now and let you know how it goes.

I appreciate the work!

**Comment by 19peaches** [comment]
I'm so sorry that I forgot to come back and report on this Mike.

It is and absolute game changer for my workflow!

Thank you soooo much for adding this feature, works perfectly in every way!
