### ISSUE TITLE
Browser Open possible?

### ISSUE THREAD

**Issue by zdarin** [mikesaintsg/laravel-mix-serve#2]
hello,
Your extension amazing can you tell me it is possible to configure after "npx mix watch" command Open Browser?

**Comment by mikesaintsg** [comment]
Thanks @zdarin! Have you tried BrowserSync? It already does that on watch, and was the main reason I came up with this extension.

This is my favorite setup:

```js
const mix = require('laravel-mix');
require('laravel-mix-serve')

const url = process.env.APP_URL
const port = process.env.SERVER_PORT

mix.browserSync(`${url}` + ':' + `${port}`)
mix.serve();
```

Of course make sure to mention your SERVER_PORT in your env file for it to work.

Let me know if that works for you or if there's something I'm missing.
