### ISSUE TITLE
Cannot access SQL on the serve?

### ISSUE THREAD

**Issue by vanyamil** [mikesaintsg/laravel-mix-serve#3]
Would love to have some suggestions how to debug this: 
If I use the serve of this package, on `npm run watch` , I get SQL connection issues. If I serve normally, everything is fine.
Running on Windows 10.

**Comment by mikesaintsg** [comment]
Hi Ivan, let's take a look at the errors that come up. Copy and paste the error message that you get, so I can take a look.

**Comment by vanyamil** [comment]
I get a 
```
SQLSTATE[HY000] [1045] Access denied for user 'redacted'@'redacted-ip' (using password: YES)
```
The username corresponds to the correct username from the .env file. The IP after the @ is my personal IP, which I think is incorrect? It should be the value of DB_HOST env variable?
